apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 34
    //buildToolsVersion "30.0.2"

    defaultConfig {
        //applicationId "com.bpointer.rkofficial"
//        applicationId "com.rkgroup.rkofficial"
        applicationId "com.rkservices.rkofficial"

        minSdkVersion 24
        targetSdkVersion 34
        //versionCode 10
        //versionName "1.8"

         versionCode 11
        versionName "1.0.1.1"

       // versionCode 4
//        versionName "1.3.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "RK_UPI_GATEWAY_KEY", "\"9af7a166-baa8-4a2f-b2da-c6a2ce795663\""

    }

    buildTypes {
        release {
            multiDexEnabled true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.1.0'
//      implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.github.castorflex.smoothprogressbar:library-circular:1.3.0'
    implementation 'androidx.viewpager2:viewpager2:1.0.0-alpha01'
    implementation "com.google.android.material:material:1.1.0-alpha07"

    implementation project(path: ':autoimageslider')//implementation 'com.github.smarteist:autoimageslider:1.4.0-appcompat'

    implementation 'com.squareup.retrofit2:retrofit:2.6.2'
    implementation 'com.squareup.okhttp3:okhttp:3.12.1'
    implementation 'com.squareup.retrofit2:converter-gson:2.6.2'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.2'

    //implementation project(path: ':multiline-collapsingtoolbar')//implementation 'net.opacapp:multiline-collapsingtoolbar:27.1.1'
    implementation "androidx.coordinatorlayout:coordinatorlayout:1.1.0"
    implementation 'io.github.chaosleung:pinview:1.4.4'//implementation 'com.chaos.view:pinview:1.4.3'
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    implementation 'in.easebuzz:android-v2:1.0.2'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    implementation 'com.github.f0ris.sweetalert:library:1.6.2'
    implementation 'com.tuyenmonkey:mkloader:1.4.0'

    // Import the Firebase BoM
    implementation platform('com.google.firebase:firebase-bom:28.4.2')

    // Add the dependency for the Firebase SDK for Google Analytics
    // When using the BoM, don't specify versions in Firebase dependencies
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'

    //implementation 'com.gpfreetech:IndiUpi:1.1'
    implementation project(path: ':IndiUpi')
    implementation 'com.android.support:multidex:2.0.1'

    implementation ("com.github.javiersantos:AppUpdater:2.7")

    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.github.invissvenska:ModalBottomSheetDialog:1.0.5'

//    implementation 'in.easebuzz:android-v2:1.0.2'

}